updated for PR and traefik, issues with currnet env file
INTO-CPS-Association/DTaaS pull request #21
Opened 2023-03-26 17:42 UTC by Artin13

There are issues with how the other group have designed the env file, we cant get information from it for our scripts and we dont want to change it because of the effect for the other groups scripts. We will be working on a solution but we first want to get your input

2023-03-26 20:54 UTC, prasadtalasila commented
@Artin13 can you be more specific about the question and show both the existing config solution and the one you want? With more information, @Omarley7 @SyntaxXeror or @DaloonOfDoom can give a clarifying answer as well.

2023-03-26 21:29 UTC, Omarley7 commented
@Artin13 I think I can deduct your issue, from your description and the code in the PR.
You simply need to add your environment variables to the [declaration file](https://en.wikipedia.org/wiki/TypeScript#Declaration_files) in `client/env.d.ts`. This way ts and intellisense can help you out. Here's an example of an updated `env.d.ts` file:

```typescript
export {};

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      REACT_APP_ENVIRONMENT: string;
      REACT_APP_URL_LIB: string;
      REACT_APP_URL_DT: string;
      REACT_APP_URL_WORKBENCH: string;
      REACT_APP_CLIENT_ID: string;
      <<<<<<<< Add more here.
    }
  }

  interface Window {
    env: NodeJS.ProcessEnv;
  }
}

```

also add the client/Public/env.js to .gitignore, to avoid any real secrets spilling out.

2023-03-28 09:35 UTC, Artin13 commented
We have done that but we got an error that says window.env is not defined

2023-03-28 20:53 UTC, prasadtalasila requested changes

2023-03-28 20:53 UTC, prasadtalasila commented on client/src/route/dashboard/Dashboard.tsx
> +          console.log('Current user: ', data?.data?.currentUser.name, data?.data?.currentUser.username);
please comment out console.log() statements. We can add [winston logger](https://github.com/winstonjs/winston) later.

2023-03-28 20:53 UTC, prasadtalasila commented on client/src/util/authentication.ts
> +        console.log('Input error');
if you expect errors, [throw](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw) an exception and put the function call in a try....catch block later.

2023-03-28 20:53 UTC, prasadtalasila commented on client/src/util/graphQL.ts
> +    const response = await axios.post<GitLabData>(gitlabUrl, { query }, {
The [apollo client](https://www.apollographql.com/docs/react/) is a really good choice. Is there any reason to use axios for graphql queries?

2023-03-28 20:53 UTC, prasadtalasila commented on servers/config/gateway/dynamic/fileConfig.yml
> +        address: "http://localhost:8090/auth"
The auth.py file is missing from servers/auth directory.

2023-03-29 11:12 UTC, prasadtalasila commented
@Artin13 and @KarstenMalle 
More commits have been made on feature/distributed-demo branch. Please rebase your branch used in this PR.

2023-03-29 11:20 UTC, closed without merging