First part of merge, private routes
INTO-CPS-Association/DTaaS pull request #40
Opened 2023-04-15 13:21 UTC by Artin13

First part of the merge. This is for the private/protected routes

2023-04-15 14:55 UTC, prasadtalasila requested changes

2023-04-15 14:55 UTC, prasadtalasila commented on client/src/index.tsx
> +      <PrivateRoute useDummyAuth={true}>
PrivateRoute must always authenticate. The option is not necessary.

2023-04-15 14:55 UTC, prasadtalasila commented on script/install.bash
> +echo \
This file has been linted in the previous two commits. You only have to make the following changes:

add the lines:
```
#install docker-compose from https://docs.docker.com/compose/install/other/
curl -SL "https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
```
remove sudo from lines - 48, 52, 56 of the file in the latest commit on the `feature/distributed-demo` branch

2023-04-15 14:55 UTC, prasadtalasila commented on client/src/components/PrivateRoute.tsx
> +class DummyAuth {
Please add both unit and integration tests for this module

2023-04-15 14:55 UTC, prasadtalasila commented on client/src/components/PrivateRoute.tsx
> +    return <div>Loading...</div>;
"User not signed in...please signin" (signin word will have a link to signin page)

2023-04-15 14:55 UTC, prasadtalasila commented on client/src/components/PrivateRoute.tsx
> +class DummyAuth {
You can call this class as Auth. You don't need to rename later.

2023-04-15 14:55 UTC, prasadtalasila commented on client/src/components/PrivateRoute.tsx
> +const PrivateRoute: React.FC<PrivateRouteProps> = ({ children, useDummyAuth = false }) => {
this line is too long; you might want to insert newline after the first equals symbol.

2023-04-15 14:57 UTC, prasadtalasila commented
@KarstenMalle , I need to check the current best practice of React.FC and React.useState(). Otherwise, rest of the review is complete.

2023-04-15 20:09 UTC, prasadtalasila commented
> @KarstenMalle , I need to check the current best practice of React.FC and React.useState(). Otherwise, rest of the review is complete.

This part looks cool. Please go ahead with the rest of the changes.

2023-04-18 12:06 UTC, prasadtalasila reviewed
already commented on the conversation thread. Gist is that the tests are failing.

2023-04-18 16:16 UTC, KarstenMalle commented
> @KarstenMalle, thanks for the update. I've used the updated client website and the authentication functionality seems to be in place. However, most of the tests fail. Please see the Github Actions [log](https://github.com/INTO-CPS-Association/DTaaS/actions/runs/4722783711/jobs/8377843768?pr=40#step:6:36). Even `yarn test` shows the same error log.

Yes sorry about that. It should be fixed now.

2023-04-18 21:45 UTC, KarstenMalle commented
> > @KarstenMalle, thanks for the update. I've used the updated client website and the authentication functionality seems to be in place. However, most of the tests fail. Please see the Github Actions [log](https://github.com/INTO-CPS-Association/DTaaS/actions/runs/4722783711/jobs/8377843768?pr=40#step:6:36). Even `yarn test` shows the same error log.
> 
> Yes sorry about that. I see the Playwright tests are also failing, I will try to fix it tonight.

Playwright tests are fixed, code climate is complaining about duplication but I think that is expected due to testing similar scenarios. Let me know if you want anything changed :)

2023-04-19 10:52 UTC, merged