Server integrable LIB MS
INTO-CPS-Association/DTaaS pull request #54
Opened 2023-05-11 12:44 UTC by ravvnen

2023-05-12 05:03 UTC, prasadtalasila requested changes
please remove all the traefik-related tests from this PR. You can fix the open [codeclimate issues](https://codeclimate.com/github/INTO-CPS-Association/DTaaS/issues) on `servers/lib` in this PR.

2023-05-12 13:51 UTC, ravvnen commented
@prasadtalasila The PR should be ready now for merge 🚀

2023-05-12 15:44 UTC, prasadtalasila requested changes

2023-05-12 15:44 UTC, prasadtalasila commented on .github/workflows/server.yml
> +      # - name: Run the linting checks
This change is not required for the scope of this PR.

2023-05-12 15:44 UTC, prasadtalasila commented on .gitignore
> +servers/config/gateway/dynamic/fileConfig_local.yml
not required as well

2023-05-12 15:44 UTC, prasadtalasila commented on servers/config/gateway/README.md
The only thing that changes in this file is port number.

2023-05-12 15:44 UTC, prasadtalasila commented on servers/config/gateway/traefik.yml
please revert changes done on this file

2023-05-12 15:44 UTC, prasadtalasila commented on servers/config/gateway/dynamic/fileConfig.yml
please use this yml file
```yml
http:
  routers:
    dtaas:
      entryPoints:
        - http
      rule: 'Host(`localhost`)'
      middlewares:
        - basic-auth
      service: dtaas

    user1:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/user1`)'
      middlewares:
        - basic-auth
      service: user1

    user2:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/user2`)'
      middlewares:
        - basic-auth
      service: user2

    vis:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/vis`)'
      service: grafana


    lib:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/lib`)'
      service: lib


  # Middleware: Basic authentication
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: "/etc/traefik/auth"
        removeHeader: true


  services:
    dtaas:
      loadBalancer:
        servers:
          - url: "http://localhost:4000"

    user1:
      loadBalancer:
        servers:
          - url: "http://localhost:8090"

    user2:
      loadBalancer:
        servers:
          - url: "http://localhost:8091"

    grafana:
      loadBalancer:
        servers:
          - url: "http://localhost:3000"

    lib:
      loadBalancer:
        servers:
          - url: "http://localhost:3001"
```

2023-05-13 16:15 UTC, ravvnen commented on servers/config/gateway/dynamic/fileConfig.yml
but lib should be at 4001 here right? i changed it to that

2023-05-13 16:27 UTC, ravvnen commented
@prasadtalasila This PR should be ready to be merged now 🎸 🤖

2023-05-14 14:07 UTC, prasadtalasila commented
The [env section](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/docs/LIB-MS.md) of `docs/LIB-MS.md` file requires updates as well.

2023-05-14 16:25 UTC, ravvnen commented on .github/workflows/server.yml
>            MODE: gitlab
tests that run with MODE:local, are given this environment variable in the relevant test, so there shouldn't be a need to add them here

2023-05-14 16:25 UTC, ravvnen commented on servers/lib/test/files.e2e-spec.ts
It is - i have just renamed it to files.service.integration.spec.ts - and then i have removed some of the tests since i came to the realization that they werent integration tests.

2023-05-14 20:04 UTC, prasadtalasila commented on servers/config/gateway/README.md
use this updated README.md

2023-05-14 20:20 UTC, prasadtalasila commented
The tests seem to be dependent on the top-level `.env` file. If we don't have a certain `.env` file, the following kind of errors come.

```
 FAIL  test/unit/files.service.unit.spec.ts (21.673 s)                                                                                                                                 
  ● Unit tests for FilesService › getLocalFiles › should return the filenames in the given directory                                                                                   
                                                                                                                                                                                       
    ENOENT: no such file or directory, scandir '/Users/<Username>/DTaaS/servers/lib/test/data/test_assets/user1'                                                                       
                                                                                                                                                                                       
      27 |     const dataPath = this.configService.get("LOCAL_PATH");                                                                                                                  
      28 |     const fullpath = join(dataPath, path);                                                                                                                                  
    > 29 |     return fs.readdirSync(fullpath);                                                                                                                                        
         |               ^                                                                                                                                                             
      30 |   }                                                                                                                                                                         
      31 |                                                                                                                                                                             
      32 |   async getGitlabFiles(path: string): Promise<string[]> {

      at FilesService.readdirSync [as getLocalFiles] (src/files/files.service.ts:29:15)
      at Object.<anonymous> (test/unit/files.service.unit.spec.ts:39:41)
```
Please see the [tests.log](https://github.com/INTO-CPS-Association/DTaaS/files/11472855/tests.log).

These tests are running in the github actions because of the env variables set on lines 34-43 of server.yml. Any test-specific configuration should be in test/ directory and not be dependent on the top-level env variables.

2023-05-14 20:27 UTC, prasadtalasila commented
I think the trouble is with `TEST_PATH='/Users/<Username>/DTaaS/servers/lib/test/data/test_assets'` variable in the env file. Please move this variable into a file in test/ and use it for tests. An easy trick is to make this variable a shell environment variable in `script/test.bash`.
You can say,
```
export TEST_PATH=$(pwd)/test/data/test_assets
```
now use can receive this variable as node process environment variable and use it in tests.

2023-05-14 20:32 UTC, prasadtalasila commented
Even after having `TEST_PATH` point to correct directory, the following errors are seen for the E2E tests.
```
making all tests ... and retrieving coverage report                                                                                                                                    
 FAIL  test/e2e/app.e2e.spec.ts (10.902 s)                                                                                                                                             
  ● End to End test for the application › should return the filename corresponding to the directory given in the query                                                                 
                                                                                                                                                                                       
    expect(received).toEqual(expected) // deep equality                                                                                                                                
                                                                                                                                                                                       
    - Expected  - 9                                                                                                                                                                    
    + Received  + 3

      Object {
    -   "data": Object {
    -     "getFiles": Array [
    -       "data",
    -       "digital twins",
    -       "functions",
    -       "models",
    -       "tools",
    -     ],
    -   },
    +   "error": "Not Found",
    +   "error": "Not Found",
    +   "message": "Cannot POST /lib%27%20or%20%27",
    +   "statusCode": 404,
      }

      35 |       .post(process.env.APOLLO_PATH)
      36 |       .send({ query });
    > 37 |     expect(response.body).toEqual(expectedResponse);
         |                           ^
      38 |   });
      39 | });
      40 |

      at Object.<anonymous> (test/e2e/app.e2e.spec.ts:37:27)

 FAIL  test/integration/files.service.integration.spec.ts (10.88 s)
  ● Integration Tests › ensure that the getFiles method of the FilesService class returns the expected array of file names when called with a specific path

    expect(received).toBeDefined()
    Received: undefined

      49 |
      50 |     expect(response.body).toBeDefined();
    > 51 |     expect(response.body.data).toBeDefined();
         |                                ^
      52 |     expect(response.body.data.getFiles).toEqual(localFiles);
      53 |   });
      54 | });

      at Object.<anonymous> (test/integration/files.service.integration.spec.ts:51:32)
```

Are these errors expected? Is there a way to fix them?

2023-05-14 20:41 UTC, prasadtalasila commented
Do `localhost:4001/lib` and `localhost:4001/lib/graphql` provide the same functionality?

2023-05-15 05:44 UTC, prasadtalasila commented on servers/lib/script/test.bash
> +export TEST_PATH=$(pwd)/test/data/test_assets
replace echo command with printf

TEST_PATH=$(pwd)/test/data/test_assets
export TEST_PATH

2023-05-15 06:38 UTC, ravvnen commented
> Do `localhost:4001/lib` and `localhost:4001/lib/graphql` provide the same functionality?
yes

I have made changes accordingly to the TEST_PATH and that should fix the problem, at least i am not able to reproduce the error on github actions that you received.

2023-05-15 11:11 UTC, ravvnen commented
@prasadtalasila - All changes from our meeting should now be fixed. Let me know if i missed anything 🚀

2023-05-16 06:58 UTC, merged