Feature/distributed demo
INTO-CPS-Association/DTaaS pull request #94
Opened 2023-09-03 11:17 UTC by astitva1905

Porting release v0.2 documentation to feature-distributed.

2023-09-03 15:17 UTC, prasadtalasila requested changes

2023-09-03 15:17 UTC, prasadtalasila commented on docs/developer/client/uml/package-diagram.puml
please keep all the puml files

2023-09-03 15:17 UTC, prasadtalasila commented on docs/thanks.md
please add your name under point 2 of **Documentation** section

2023-09-03 15:17 UTC, prasadtalasila commented on docs/user/servers/lib/LIB-MS.md
please do not change this file

2023-09-03 15:17 UTC, prasadtalasila commented on packages/client/README.md
please do not add the `packages` directory

2023-09-03 15:17 UTC, prasadtalasila commented on script/env.sh
> +sudo -H pip3 install python-markdown-math
sudo -H pip3 mkdocs-open-in-new-tab
sudo -H pip3 mkdocs-with-pdf
sudo -H pip3 qrcode

2023-09-03 15:17 UTC, prasadtalasila commented on script/env.sh
> +sudo -H pip install mkdocs
sudo -H pip3 install mkdocs

2023-09-03 15:17 UTC, prasadtalasila commented on ssl/README.md
please keep everything under `ssl/` directory

2023-09-03 15:23 UTC, prasadtalasila commented
When you are done please use the [docs/PUBLISH.md](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/docs/PUBLISH.md) to publish the docs to your `webpage-docs` branch. You can use this branch to host [project docs](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages). The same technique is used to host the [DTaaS documentation](https://into-cps-association.github.io/DTaaS/).
I can check your docs page to see the final result of changes. Thanks.

2023-09-07 10:53 UTC, astitva1905 commented on deploy/vagrant/single-machine/README.md
> +wget https://raw.githubusercontent.com/INTO-CPS-Association/DTaaS/release-v0.2/deploy/vagrant/route.sh
Replaced suggestion with line 24

2023-09-07 10:56 UTC, astitva1905 commented on deploy/vagrant/two-machine/README.md
> +wget https://raw.githubusercontent.com/INTO-CPS-Association/DTaaS/release-v0.2/deploy/vagrant/two-machine/services.sh
Replaced line at 49

2023-09-07 10:58 UTC, astitva1905 commented on deploy/vagrant/two-machine/README.md
> +wget https://raw.githubusercontent.com/INTO-CPS-Association/DTaaS/release-v0.2/deploy/vagrant/route.sh
Replaced line at 51

2023-09-07 10:58 UTC, astitva1905 commented on deploy/vagrant/two-machine/README.md
> +wget https://raw.githubusercontent.com/INTO-CPS-Association/DTaaS/release-v0.2/deploy/vagrant/route.sh
Replaced line at 72

2023-09-07 11:09 UTC, astitva1905 commented on docs/admin/servers/lib/LIB-MS.md
> +TEST_PATH='/Users/<Username>/DTaaS/servers/lib/test/data/test_assets'
Removed lines 47,48

2023-09-07 11:13 UTC, astitva1905 commented on docs/admin/trial.md
> +wget https://github.com/INTO-CPS-Association/DTaaS/releases/download/v0.2.0/single-script-install.sh
Replaced line 7

2023-09-07 11:14 UTC, astitva1905 commented on docs/admin/vagrant/single-machine.md
> +wget https://raw.githubusercontent.com/INTO-CPS-Association/DTaaS/release-v0.2/deploy/vagrant/route.sh
Replaced line 24

2023-09-07 11:16 UTC, astitva1905 commented on docs/admin/vagrant/two-machines.md
> +wget https://raw.githubusercontent.com/INTO-CPS-Association/DTaaS/release-v0.2/deploy/vagrant/two-machine/services.sh
Replaced line 45

2023-09-07 11:16 UTC, astitva1905 commented on docs/admin/vagrant/two-machines.md
> +wget https://raw.githubusercontent.com/INTO-CPS-Association/DTaaS/release-v0.2/deploy/vagrant/route.sh
Replaced line 47

2023-09-07 11:17 UTC, astitva1905 commented on docs/admin/vagrant/two-machines.md
> +wget https://raw.githubusercontent.com/INTO-CPS-Association/DTaaS/release-v0.2/deploy/vagrant/route.sh
Replaced line 68

2023-09-07 11:23 UTC, astitva1905 commented on docs/thanks.md
Just added full name as Point 2, please let me know if any text to be added along with that.

2023-09-07 13:45 UTC, prasadtalasila reviewed
@astitva1905 I have checked upto `docs/admin/vagrant/base-box.md`. Please check the suggested changes. Thanks.

2023-09-07 13:45 UTC, prasadtalasila commented on deploy/vagrant/single-machine/README.md
> +1. Create [**dtaas** Vagrant box](../make_boxes/dtaas/README.md). Copy _vagrant_ SSH private key here. This shall be useful for logging into the vagrant machine created for single-machine deployment.
Replace text:

```
Create [**dtaas** Vagrant box](../make_boxes/dtaas/README.md). You would have created an SSH key pair - _vagrant_ and _vagrant.pub_ for the vagrant box. The _vagrant_ is the private SSH key and is needed for the next steps. Copy _vagrant_ SSH private key into the current directory (`deploy/vagrant/single-machine`). This shall be useful for logging into the vagrant machine created for single-machine deployment. 

```

2023-09-07 13:45 UTC, prasadtalasila commented on deploy/vagrant/two-machine/README.md
> +wget https://raw.githubusercontent.com/INTO-CPS-Association/DTaaS/feature/distributed-demo/deploy/vagrant/two-machine/services.sh
wget https://raw.githubusercontent.com/INTO-CPS-Association/DTaaS/feature/distributed-demo/deploy/vagrant/route.sh

2023-09-07 13:45 UTC, prasadtalasila commented on deploy/vagrant/two-machine/Vagrantfile
> +      #node.vm.provision "shell", privileged: false, path: opts["script"]
please remove this commented line

2023-09-07 13:45 UTC, prasadtalasila commented on docs/admin/client/CLIENT.md
> +https:foo.com/<username>/terminals/main'
please remove the single-quote at the end of the line

2023-09-07 13:45 UTC, prasadtalasila commented on docs/admin/host.md
> +Update the _deploy/config/lib_ of the library microservice. The simplest possibility is to use `local` mode with the following example. The filepath is the absolute filepath to `files/` directory.
Replace with this text:

```
The library microservice requires configuration. A template of this configuration file is given in _deploy/config/lib_ file. Please modify this file as per your needs. 

An example `.env` file is given below. The simplest possibility is to use `local` mode with the following example. The filepath is the absolute filepath to `files/` directory. You can copy this configuration into _deploy/config/lib_ file to get started.
```

2023-09-07 13:45 UTC, prasadtalasila commented on docs/admin/servers/lib/LIB-MS.md
> +## Developer Commands
Please remove the **Developer Commands** section completely. Keep the next section - **Service Endpoint**.

2023-09-07 17:36 UTC, prasadtalasila reviewed
@astitva1905 The review is now complete. Thanks for making the changes.

2023-09-07 17:36 UTC, prasadtalasila commented on docs/developer/system/DTaaS.drawio
Please revert the change in file permissions. You may have to set the default file permissions in the windows git client. Otherwise, all file permission changes get reflected as a new changes in files. It is not desirable.

2023-09-07 17:36 UTC, prasadtalasila commented on servers/lib/README.md
>  ## Developer Commands
Developer Commands ---> User Commands

2023-09-07 17:36 UTC, prasadtalasila commented on docs/admin/vagrant/single-machine.md
> +1. Create [**dtaas** Vagrant box](./base-box.md). Copy _vagrant_ SSH private key into _deploy/vagrant/single-machine_. This shall be useful for logging into the vagrant machine created for single-mac
Revised sentence:

```
Create [**dtaas** Vagrant box](../make_boxes/dtaas/README.md). You would have created an SSH key pair - _vagrant_ and _vagrant.pub_ for the vagrant box. The _vagrant_ is the private SSH key; Copy _vagrant_ SSH private key into the current directory (`deploy/vagrant/single-machine`). This shall be useful for logging into the vagrant machine created for single-machine deployment.
```

2023-09-07 17:36 UTC, prasadtalasila commented on docs/admin/vagrant/two-machines.md
> +| Influx visualization service | services.foo.com |
InfluxDB and visualization service

2023-09-07 17:36 UTC, prasadtalasila commented on docs/admin/vagrant/two-machines.md
> +InfluxDB webUI will be available at: _services.foo.com_. The RabbitMQ service and its management interface shall be available at 5672 and 15672 TCP ports respectively. The Grafana service shall be av
Revised text:
```
InfluxDB and visualization service will be available at: _services.foo.com_. The RabbitMQ service and its management interface shall be available at 5672 and 15672 TCP ports respectively. The Grafana service shall be available at TCP port 3000.
```

2023-09-08 07:57 UTC, astitva1905 commented on ssl/certificates.bash
Sir what should the final file permissions be ?

2023-09-08 08:49 UTC, merged